initial commit
anaconda-distribution/anaconda-linter pull request #259
Opened 2023-07-07 00:28 UTC by Arishamays1

This PR is related to issue #227. When run, this amendment returns a more organized output that flows much more smoothly:

### Example Output:
``` 
The following problems have been found:

===== WARNINGS ===== 
- opentelemetry-python-feedstock/recipe/meta.yaml:1: missing_license_file: The recipe is missing the `about/license_file` or `about/license_url` key.
- opentelemetry-python-feedstock/recipe/meta.yaml:71: python_build_tool_in_run: output "opentelemetry-api": The python build tool setuptools is in run depends
- opentelemetry-python-feedstock/recipe/meta.yaml:1: missing_description: The recipe is missing a description

===== ERRORS ===== 
- opentelemetry-python-feedstock/recipe/meta.yaml:1: missing_documentation: The recipe is missing a doc_url or doc_source_url
- opentelemetry-python-feedstock/recipe/meta.yaml:0: missing_section: The about section is missing.
- opentelemetry-python-feedstock/recipe/meta.yaml:1: missing_dev_url: The recipe is missing a dev_url
- opentelemetry-python-feedstock/recipe/meta.yaml:1: missing_license: The recipe is missing the `about/license` key.
- opentelemetry-python-feedstock/recipe/meta.yaml:1: missing_license_family: The recipe is missing the `about/license_family` key.
- opentelemetry-python-feedstock/recipe/meta.yaml:1: missing_summary: The recipe is missing a summary
- opentelemetry-python-feedstock/recipe/meta.yaml:1: patch_must_be_in_build: patch must be in build when source/patches is set.
- opentelemetry-python-feedstock/recipe/meta.yaml:1: missing_home: The recipe is missing a homepage URL

==== Ending Report: =====
8 Errors and 3 Warnings were found
Errors were found 
```

2023-07-07 14:49 UTC, marcoesters requested changes
General comments:

1. You need to run pre-commit. You can install it using `brew install pre-commit` and then run `pre-commit run --all`.
2. Your current PR removes all `INFO` outputs. If a user doesn't want to see them, they can use the `--severity` flag to skip them - we shouldn't make that decision for them.
3. There is redundancy in the output. The final report shows the number of errors and then in the end, it says "Errors were found". You should remove these parts in `run.py`

2023-07-07 14:49 UTC, marcoesters commented on anaconda_linter/lint/__init__.py
> +        messages_sorted = {sev: [] for sev in Severity}
Please re-add line 582 of the old code. It sorts the messages by file name and line number. Otherwise, they are sorted by the lint check that is performed.

That being said, I think `messages_grouped` may be a better name, semantically for what you're doing here.

2023-07-07 14:49 UTC, marcoesters commented on anaconda_linter/lint/__init__.py
> +        report_sections = []
This is probably unnecessary. You can also just append to the report string instead.

2023-07-07 14:49 UTC, marcoesters commented on anaconda_linter/lint/__init__.py
> +                    + "\n".join(
This is missing the verbose output in the original code.

2023-07-07 14:49 UTC, marcoesters commented on anaconda_linter/lint/__init__.py
> +        report += '\n'f"==== Ending Report: =====\n{num_errors[Severity.ERROR]} Error{'s' if num_errors[Severity.ERROR] != 1 else ''} and {num_errors[Severity.WARNING]} Warning{'s' if num_errors[Seve
"Final Report" I think sounds better - the colon isn't needed either.

Also, what happens when nothing was found? This is a very verbose way of saying "everything is okay".

It may be also be easier to read when output this way:

==== Final Report ====
Warnings: 3
Errors: 8

2023-09-15 16:20 UTC, varlackc commented
There are currently some merge conflicts that will have to be resolved before approval.

2023-11-14 18:41 UTC, schuylermartin45 requested changes

2023-11-14 18:41 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +        num_errors: dict[Severity, int] = {sev: 0 for sev in [Severity.ERROR, Severity.WARNING]}
```
struct LintMessageInfo {
  LintMessage[] message;
  int count = 0;
  ...
}
...
dict[Severity, LintMessageInfo] = {}
```

2023-11-14 18:41 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +        num_errors: dict[Severity, int] = {sev: 0 for sev in [Severity.ERROR, Severity.WARNING]}
Iteration: get the len(messages). Discard count, reduce to 1 dictionary that contains a list.

2023-11-14 18:41 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +            f"==== Final Report: =====\n"
Nitpick: Both sides should have the same number of `=`s

2023-11-14 18:41 UTC, schuylermartin45 commented on tests/conftest.py
> +# def check_output( ):
Don't include commented code

2023-11-14 18:41 UTC, schuylermartin45 commented on tests/test_lint.py
> +from typing import List
As mentioned before, let's delete `List` and use `list`

2023-11-14 18:41 UTC, schuylermartin45 commented on tests/test_lint.py
> +    messages: List[LintMessage] = [
Make this `Final[list[...]]`

2023-11-14 18:41 UTC, schuylermartin45 commented on tests/test_lint.py
> +    report: str = Linter.get_report(messages)
Also a `Final`

2023-11-14 18:41 UTC, schuylermartin45 commented on tests/test_lint.py
> +    lint_check: str = (
```
assert report == (
  "foo bar string"
   ...
)
```

2023-11-16 23:13 UTC, Arishamays1 commented on anaconda_linter/lint/__init__.py
> +                    + "\n".join(
Thanks for the suggestions! The verbose feature has been reinstated

2023-11-16 23:14 UTC, Arishamays1 commented on anaconda_linter/lint/__init__.py
> +        num_errors: dict[Severity, int] = {sev: 0 for sev in [Severity.ERROR, Severity.WARNING]}
Thanks Schuyler, went ahead and added a few amendments :)

2023-11-16 23:14 UTC, Arishamays1 commented on anaconda_linter/lint/__init__.py
> +        messages_grouped: dict[Severity, List[LintMessage]] = {sev: [] for sev in Severity}
Noted!

2023-11-16 23:14 UTC, Arishamays1 commented on tests/test_lint.py
> +from typing import List
Got it!

2023-11-16 23:16 UTC, Arishamays1 commented on tests/test_lint.py
> +    messages: List[LintMessage] = [
Done!

2023-11-16 23:16 UTC, Arishamays1 commented on tests/test_lint.py
> +    lint_check: str = (
Changed! 
thanks

2023-11-16 23:16 UTC, Arishamays1 commented on tests/test_lint.py
> +    report: str = Linter.get_report(messages)
done!

2023-11-16 23:17 UTC, Arishamays1 commented on tests/conftest.py
> +# def check_output( ):
Oops! Removed!

2023-11-17 16:57 UTC, schuylermartin45 requested changes

2023-11-17 16:57 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +from typing import Any, Final, List, NamedTuple, Optional, Tuple, Union
```suggestion
from typing import Any, Final, NamedTuple, Optional, Union
```
We should be refraining from using the capitalized versions of the common types

2023-11-17 16:57 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +from dataclasses import dataclass, field
I don't see these used in this file and I am very concerned why the linter did not pick up on that.

2023-11-17 16:57 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +from dataclasses import dataclass, field
It looks like the `.pylintrc` file skips the `__init__.py` files by design. It is not typical that these files have code in them.

```
# Tells whether we should check for unused import in __init__ files.
init-import=no
```

I will try to fix this today before I'm out for the holiday.

2023-11-17 16:57 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +from dataclasses import dataclass, field
This has gotten merged: https://github.com/anaconda-distribution/anaconda-linter/pull/317

You will want to `git pull -r origin main` before making any more changes.

2023-11-17 16:57 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +from typing import Any, Final, List, NamedTuple, Optional, Tuple, Union
(In favor of `list[]` and `tuple[]`)

2023-11-17 16:57 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +class SeverityInfo(NamedTuple):
Classes should have a description comment
```
class SeverityInfo(NamedTuple):
    """
    <Explanation/description of this structure>
    """
```

2023-11-17 16:57 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +        severity_data: dict[Severity, list[LintMessage]] = {sev: [] for sev in Severity}
I'm sure you are aware, but let's move towards 
```suggestion
        severity_data: dict[Severity, list[LintMessage]] = {}
```
And perform the necessary check changes below.

2023-11-17 16:57 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +                severity_section = f"\n===== {sev.name.upper()}S ===== \n"
```suggestion
                severity_section = f"\n===== {sev.name.upper()}S =====\n"
```

2023-11-28 18:53 UTC, Arishamays1 commented on anaconda_linter/lint/__init__.py
> +class SeverityInfo(NamedTuple):
Removed the class itself as it is outdated and unused.

2023-11-28 18:54 UTC, Arishamays1 commented on anaconda_linter/lint/__init__.py
> +from dataclasses import dataclass, field
got it!

2023-11-29 20:35 UTC, schuylermartin45 requested changes

2023-11-29 20:35 UTC, schuylermartin45 commented on tests/test_lint.py
> +        "\n===== WARNINGS ===== \n"
This whitespace keeps on coming back from the grave.

2023-11-29 20:35 UTC, schuylermartin45 commented on tests/test_lint.py
> +from typing import Final, List
Let's remove the `List` here as well. Sorry for not catching it in this file.

2023-11-29 20:35 UTC, schuylermartin45 commented on tests/test_lint.py
> +def test_get_report():
As a sanity check, let's also make a unit test case for when the report engine does not get any error or warning messages.

Also this should be type annotated to return `None`

2023-11-29 20:37 UTC, schuylermartin45 commented on anaconda_linter/lint/__init__.py
> +            info = severity_data.get(sev, [])
We should get in the habit of "returning early" when a condition is not met over allocating data structures we don't end up using.

So instead, check if the `sev` is in the dictionary and skip the rest of the loop if it isn't:
```
for sev in [....]:
  if info not in severity_data:
    continue
  info = severity_data[sev]
```

2023-12-04 17:44 UTC, Arishamays1 commented on anaconda_linter/lint/__init__.py
> +            info = severity_data.get(sev, [])
Got it!

2023-12-05 22:21 UTC, schuylermartin45 approved these changes

2023-12-05 22:24 UTC, schuylermartin45 commented
`build-recipe` is failing for some unrelated reason, appears to be an issue with the latest version of `conda-build`(?). I'll look into it later.

2023-12-05 22:24 UTC, merged